EVENT_DESTROYED               = 1
EVENT_BATTLE_DESTROYED        = 2
EVENT_BATTLE_STARTED          = 3
EVENT_BATTLE_ENDED            = 4
EVENT_PRE_DAMAGE_CALCULATION  = 5
EVENT_POST_DAMAGE_CALCULATION = 6
